### ISSUE TITLE
How to get just live youtube video url or m3u8 playlist file?

### ISSUE THREAD

**Issue by yashodhank** [herowinb/live-dl#8]
Thank you so much for sharing your mod and in depth details for automation. Love it!

Can you suggest way to extract just YouTube Live URL instead of downloading the video, I want to extract just URL portion of course without breaking automation part.

Thank you

**Comment by herowinb** [comment]
Sorry for late response. 

> Can you suggest way to extract just YouTube Live URL instead of downloading the video, I want to extract just URL portion of course without breaking automation part.

So you only want json file (m3u8 link) from Youtube Live URL right ?

**Comment by yashodhank** [comment]
No worries, yes. I am looking forward to extract `.m3u8` URL from json response. It will be really great as I will be able to monitor my primary youtube channel and as soon as I go live using ffmpeg and m3u8 file I will be able to go live on other channel as well. :)

**Comment by herowinb** [comment]
I created new func. You want it show like this ? 
Work with Metadata mode.

![image](https://user-images.githubusercontent.com/8396689/132129279-256c330d-c8f9-4930-9355-87c42c1771c0.png)

[live-dl.zip](https://github.com/herowinb/live-dl/files/7111706/live-dl.zip)

**Comment by yashodhank** [comment]
I have downloaded `https://github.com/herowinb/live-dl/blob/get_m3u8_link/live-dl` and trying to run as follows:
```
./live-dl https://www.youtube.com/channel/UC9OM-qeiYIPtAkBe9veG5uw/live -m metadat
[Mon Sep  6 00:43:13 IST 2021] No config.yml, 'cp config.example.yml config.yml' and rerun this script.
```

config.yml
```
config:
  # Runing mode
  #
  # - download: default mode, monitor URL and download when available
  # - metadata: download JSON metadata only
  # - notifier: only send notifications
  mode: metadata

  # Output directory
  # There's no need to quote or escape your path, examples:
  #
  # - ./downloads
  # - /home/My Recordings
  # - ~/Downlaods
  # - ~/Files/VTuber Videos
  # - ~/Downloads/VTuber Recordings
  #
  # All examples above should work
  output: ./downloads

  # Loop interval, unit: second
  # Default: 10
  interval: 10

  # Skip dependency check
  # Default: false
  skip_check: false

  # Skip converting TS file to MP4. This can save your time on lowend machines
  # Default: false
  skip_convert: false

  # Skip embedding metadata in videos.
  # Default: false
  skip_metadata: false

  # Skip sending emails when live starts/ends
  # Default: false
  skip_email: false

  # Skip sending Slack notifications when live starts
  # Default: false
  skip_slack: false

  # Skip sending notifications to specific Telegram channels (if available) when live starts
  # Default: false
  skip_telegram: false

  # Run script only once without monitoring
  # Default: false
  one_time: false

  # Set timezone for notifications
  # Default: Asia/Tokyo
  timezone: Asia/Tokyo

  # Filter video titles. Only works with channel URL in stream download mode
  #
  # - Can be single string or regex expression. ie. ASMR|歌
  # - Can be overrided by passing --filter option
  #
  # Default: "" (download all streams)
  filter: ""

  # Use youtube-dl to handle livestreams instead of streamlink
  # Default: false
  ytdl_stream: false

  # Passing additional options to youtube-dl. options should be quoted
  # Default: ""
  ytdl_args: ""

  # Passing additional options to streamlink. options should be quoted
  # Default: ""
  streamlink_args: ""

  # Choose your email provider. I recommend AWS SES
  # Default: ses
  email_provider: ses
  mailgun:
    # Find your private API key at https://app.mailgun.com/app/account/security/api_keys
    api: key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  ses:
    access: AKxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  slack:
    # Create your webhook at https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
    webhook: https://hooks.slack.com/services/
  telegram:
    # Obtian your bot API from @BotFather
    bot: 000000000:xxxxxxxxx
    # Get channel ID via:
    # https://api.telegram.org/bot<API-access-token>/getUpdates?offset=0
    channel: 0000000000000
  discord:
    # Create your webhook at https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
    webhook: https://discord.com/api/webhooks/

# Define your own channel map.
# Channel map can provide channel specific options
map:
  - name: Sparanoid
    mode: metadata
    youtube: https://www.youtube.com/channel/UCxRuOqAAVo-f516Gygjh_wA
#    bilibili: https://live.bilibili.com/456117
#    telegram: -1001437419680
#    timezone: America/Los_Angeles
#   discord: https://discord.com/api/webhooks/
```
